//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCS.DisruptOp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disrupt
    {
        public int Id { get; set; }
        public string CarrierCode { get; set; }
        public string Number { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public System.DateTime STD { get; set; }
        public System.DateTime STA { get; set; }
        public string Severity { get; set; }
        public decimal PaxDLOriginal { get; set; }
        public decimal PaxDLLive { get; set; }
        public string Reason { get; set; }
        public Nullable<decimal> Recovery { get; set; }
        public string StaffComms { get; set; }
        public string CustomerComms { get; set; }
        public string Event { get; set; }
    }
}
